/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Desktop;

import BusinessLogic.Validaciones;
import javax.swing.JOptionPane;
import BusinessEntities.Viaje;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import BusinessLogic.ViajeLogic;

/**
 *
 * @author Santiago
 */
public class frmDatos extends javax.swing.JFrame {

    /**
     * Creates new form frmDatos
     */
    public ViajeLogic viaje;
    
    public frmDatos() {
        initComponents();
        this.setLocationRelativeTo(null);  
    }
     
    
    public frmDatos(ViajeLogic viajeActual) {
        initComponents();
        viaje = viajeActual;
        this.setLocationRelativeTo(null);  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDNI = new javax.swing.JLabel();
        lblNumTC = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtNumTC = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos del Cliente");
        setName("Datos del Cliente"); // NOI18N
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        lblDNI.setText("DNI");

        lblNumTC.setText("Nº Tarjeta de Crédito");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lblDNI))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNumTC)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtDNI)
                    .addComponent(txtNumTC, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 173, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDNI)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumTC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        lblDNI.getAccessibleContext().setAccessibleName("lblDNI");
        lblNumTC.getAccessibleContext().setAccessibleName("lblNumTC");
        txtDNI.getAccessibleContext().setAccessibleName("txtDNI");
        txtNumTC.getAccessibleContext().setAccessibleName("txtNumTC");
        btnAceptar.getAccessibleContext().setAccessibleName("btnAceptar");
        btnCancelar.getAccessibleContext().setAccessibleName("btnCancelar");

        getAccessibleContext().setAccessibleName("frmDatos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
                dispose();
                frmViaje viaje = new frmViaje();
                viaje.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        Validaciones valida = new Validaciones();
        
        boolean DNI, TC;
        TC = valida.TC(txtNumTC.getText());
        DNI = valida.DNI(txtDNI.getText());
        if (DNI == true && TC == true)
        {
            frmCosto costo = new frmCosto(viaje);
            costo.setVisible(true);
            this.setVisible(false);
        }
        else
        {
           if (DNI == false)
                {
                    if (TC == false)
                    {
                        //mensaje error DNI y TC
                        JOptionPane.showMessageDialog(this,"- DNI incorrecto\n- Nº de Tarjeta de Crédito incorrecto","Error",JOptionPane.ERROR_MESSAGE);
                    }
                    else
                    {
                        //mensaje error DNI
                        JOptionPane.showMessageDialog(this,"- DNI incorrecto","Error",JOptionPane.ERROR_MESSAGE);
                    }
                }
        
                else
                {
                    //mensaje error TC
                    JOptionPane.showMessageDialog(this,"- Nº de Tarjeta de Crédito incorrecto","Error",JOptionPane.ERROR_MESSAGE);
                }
        }
        
        
        
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
         int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
        Toolkit.getDefaultToolkit().beep();
        System.out.println("ENTER pressed");
    }
    }//GEN-LAST:event_formKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDatos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblNumTC;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNumTC;
    // End of variables declaration//GEN-END:variables
}
